name: badges
on:
  schedule:
    - cron: "8 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  badges:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - name: update badges
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          export NUM_CITES=$(jq '.cited_by."table" | .[] | .citations.all' data/google-scholar.json | cut -d "n" -f1 | tr -d \\n)
          curl "https://img.shields.io/badge/Google%20Scholar-${NUM_CITES}%20citations-red?color=4285F4&logoColor=4285F4&logo=googlescholar" -o badges/google-scholar.svg
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add badges/
          git commit --allow-empty -m 'update badges'
          git push
