name: google-scholar
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - name: update google scholar data
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          curl "https://serpapi.com/search.json?engine=google_scholar_author&author_id=${SCHOLAR_ID}&api_key=${API_KEY}" -o data/google-scholar.json
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add data/
          git commit --allow-empty -m 'update google scholar data'
          git push
