name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          curl "https://serpapi.com/search.json?engine=google_scholar_author&author_id=${SCHOLAR_ID}&api_key=${API_KEY}" -o scholar.json
          cat scholar.json | jq '.cited_by."table" | .[] | .citations.all'
