name: main
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: badges
      - name: badges
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          curl "https://serpapi.com/search.json?engine=google_scholar_author&author_id=${SCHOLAR_ID}&api_key=${API_KEY}" -o badges/scholar.json
          export NUM_CITES=$(jq '.cited_by."table" | .[] | .citations.all' badges/scholar.json | cut -d "n" -f1 | tr -d \\n)
          curl "https://img.shields.io/badge/Google%20Scholar-${NUM_CITES}%20citations-red?color=4285F4&logoColor=4285F4&logo=googlescholar" -o badges/googleScholar.svg
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add badges/
          git commit --allow-empty -m 'update from main branch'
          git push
