name: test
on:
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: data
      - name: update raw data
        env:
          OPENXBL_API_KEY: ${{ secrets.OPENXBL_API_KEY }}
        run: |
          mkdir -p data/
          curl --header "X-Authorization: ${OPENXBL_API_KEY}" "https://xbl.io/api/v2/account" -o raw/xbox.json
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add raw/
          git commit --allow-empty -m 'update raw data'
          git push
